### PR TITLE
[WIP] Hiring exercise for 2016: Galactic Recursion

### PR DESCRIPTION
**Pull request by darabos**
This is running on http://ramhegy:8000/hiring/galactic.html, so you can take it for a spin.

The epilogue is not written yet. The visualizations are missing. I just want your help to get the problems right before investing time to polish the text and the graphics. (But feel free to comment on the text too.)

When the program gives wrong results, I log a helpful message in the JavaScript console. This is a little reward for the more inquisitive players. Also useful for testing.

Note that this repository is public. Anyone in the world can read this code review. (I think this is not a significant problem for hiring. Last year the HTML contained the correct answers, and it was fine.)

### CODE REVIEW

**Comment by darabos** [comment]
Observations from @gaborfeher:
 - We should add a super simple first task. The current first task is quite complex.
 - Make it clear with the current first task (dials) that the user code can call `validateDial`. (This is mentioned in a comment, but we should highlight it in the text too.)

Thanks!

**Comment by darabos** [comment]
PTAL

It has the all-new exercises that we came up with yesterday. Available at: http://ramhegy:8000/hiring/galactic.html

**Comment by xandrew-lynx** [comment]
Cool!

Some comments:
- not sure I like the comment that "the login was disabled and now accepts 00000 as a valid password". It's kind of in weird contrast with the fact that this happens to be the right password for the challenge.
- This pi computation task made me think that calling it an interactive coding exercise is misguiding for this problem. Maybe we should call it interactive problem solving exercise? Along the same lines, when we ask for source, we should ask for more general ideas instead.
- I'm not fully sure how understandable are the tasks if I didn't know them already... For the cellular automata, maybe include a link that explains these kind of automata? For the circuit, I don't know how, but somehow we should make it more clear that a circuit is really an undirected graph, I don't think it's that clear.

**Comment by darabos** [comment]
> Some comments:

Thanks, I've tried to address these. I've reverted the change to `hiring/index.html`, so we can do a dark launch now. And I'm doing the dark launch!

**Comment by gaborfeher** [comment]
Oh, I wanted to comment but forgot. I'd prefer if the invitation of the
user to send contact had a less negative spin. Now it's like join the evil
machines = join us. I don't know how big deal this is, just mentioning it.
Otherwise I like it very much!

**Comment by darabos** [comment]
It's live! http://rnd.lynxanalytics.com/hiring/galactic.html

> Oh, I wanted to comment but forgot. I'd prefer if the invitation of the user to send contact had a less negative spin. Now it's like join the evil machines = join us. I don't know how big deal this is, just mentioning it.

I thought it was more neutral. ("Sure, let's be "friends". I'll hack into your logs anyway.") But I would like to be less negative with the ending. Like if you solve the last puzzle, your reward should be something better at least. If anyone has any specific ideas, it's never too late to fix this.

**Comment by xandrew-lynx** [comment]
Olah Gabornak nem ugrott be a pis feladat, meg eleg sok gondolkodas utan sem. Ebbol ket (kulon-kulon is megfontolando) lehetseges kovetkeztetes jut eszembe.

Egy, a pis feladat nem eleg jo, vegyuk ki vagy javitsuk meg valahogy. Egy otlet, hogy ne rogzitsuk a szohosszt, hanem a valasz akkora kell legyen, mint a kerdes. Pl lehetnenek ezek a peldak:
  '31415': '92653',
  '31': '41',
  '415': '926',
  '15926': '53589',

Ketto, nem akarunk safety exitet beszerelni? Azaz ha valaki nem tud megoldani egy feladatot, akkor atugorhassa. Persze errol ertesulnenk... De lehet ez valahogy elveszi ezt a jatekelmenyt, hogy ha nem tudsz megoldani egy feladatot, akkor nem mehetsz tovabb. Mit gondoltok?

**Comment by xandrew-lynx** [comment]
Another idea for the pi: how about popping up more hints - as in more pairs - with time?

**Comment by darabos** [comment]
https://cloudplatform.googleblog.com/2016/03/calculating-and-searching-500-billion-digits-of-Pi.html

Maybe let's just come up with a simple programming exercise instead. When you see a code editor I think it's natural to think only of coding solutions. I'll try to think of something. Let's talk in the afternoon.

**Pull request merged**
